Adds Screenshot testing with Roborazzi (#876)
* Adds screenshot tests using Roborazzi (Robolectric Native Graphics)

- Adds Roborazzi to convention plugins
- Adds Screenshot helper in :core-testing
- Creates screenshot suites for :app and :feature-foryou


* CI and spotless


* Moves :app tests to testDemo and makes NiaAppScreenSizesScreenshotTests prettier


* CI: Moves local tests to their own step


* CI: Adds --rerun to screenshot task


* CI: Moves screenshots before local tests


* CI: Fixes wrong if statement in workflow


* CI WIP: trying to trigger the push step


* CI: Re-enables roborazzi verification


* Fixes flaky screenshot tests by setting LocalInspectionMode on


* CI: screenshot commits now use the original author intead of bot account


* CI: Disables globbing because file_pattern didn't work


* CI: Trying new file pattern for png files


* CI: Adds a check for forks


* 🤖 Updates screenshots

* Code review: toml cleanup, comments


* Use new github.event.pull_request.head.repo.fork

Co-authored-by: Simon Marquis <contact@simon-marquis.fr>

* Uses Robolectric qualifiers to set the dpi, adds section to README


* Spotless


* Delegates creation of repository to Hilt in test


* Revert "Use new github.event.pull_request.head.repo.fork"


* 🤖 Updates screenshots

* Empty commit to trigger GHA on main branch


* Makes time zones deterministic in screenshot tests


* Increases GMD timeout to 90m, but it has to be reduced


---------

Co-authored-by: Simon Marquis <contact@simon-marquis.fr>

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -13,7 +13,7 @@ concurrency:
 jobs:
   build:
     runs-on: ubuntu-latest
-    timeout-minutes: 60
+    timeout-minutes: 90
 
     steps:
       - name: Checkout
@@ -43,9 +43,6 @@ jobs:
       - name: Build all build type and flavor permutations
         run: ./gradlew assemble
 
-      - name: Run local tests
-        run: ./gradlew testDemoDebug testProdDebug
-
       - name: Upload build outputs (APKs)
         uses: actions/upload-artifact@v3
         with:
@@ -58,6 +55,65 @@ jobs:
         with:
           name: lint-reports
           path: '**/build/reports/lint-results-*.html'
+
+  test:
+    runs-on: ubuntu-latest
+
+    permissions:
+      contents: write
+
+    timeout-minutes: 60
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Validate Gradle Wrapper
+        uses: gradle/wrapper-validation-action@v1
+
+      - name: Copy CI gradle.properties
+        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'zulu'
+          java-version: 17
+
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v2
+
+      - name: Run all local screenshot tests (Roborazzi)
+        id: screenshotsverify
+        continue-on-error: true
+        run: ./gradlew verifyRoborazziDemoDebug
+
+      - name: Prevent pushing new screenshots if this is a fork
+        id: checkfork
+        continue-on-error: false
+        if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Screenshot tests failed, please create a PR in your fork first." && exit 1
+
+      # Runs if previous job failed
+      - name: Generate new screenshots if verification failed and it's a PR
+        id: screenshotsrecord
+        if: steps.screenshotsverify.outcome == 'failure' && github.event_name == 'pull_request'
+        run: |
+          ./gradlew recordRoborazziDemoDebug
+
+      - name: Push new screenshots if available
+        uses: stefanzweifel/git-auto-commit-action@v4
+        if: steps.screenshotsrecord.outcome == 'success'
+        with:
+          file_pattern: '*/*.png'
+          disable_globbing: true
+          commit_message: "🤖 Updates screenshots"
+
+      # Run local tests after screenshot tests to avoid wrong UP-TO-DATE. TODO: Ignore screenshots.
+      - name: Run local tests
+        if: always()
+        run: ./gradlew testDemoDebug testProdDebug
 
       - name: Upload test results (XML)
         if: always()
@@ -77,7 +133,7 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      
+
       - name: Copy CI gradle.properties
         run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
 
@@ -113,7 +169,7 @@ jobs:
   androidTest-GMD:
     needs: build
     runs-on: macOS-latest # enables hardware acceleration in the virtual machine
-    timeout-minutes: 55
+    timeout-minutes: 90
 
     steps:
       - name: Checkout
