Fix graphUpdate naming in workflow

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -78,7 +78,7 @@ jobs:
           commit_message: "🤖 Updates baselines for Dependency Guard"
 
       - name: Update Graphs
-        run: ./gradlew updateGraph
+        run: ./gradlew graphUpdate
 
       - name: Check Graphs
         id: graphs_verify
@@ -89,7 +89,7 @@ jobs:
         continue-on-error: false
         if: steps.graphs_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
         run: |
-          echo "::error::Check Graphs failed, please update graphs with: ./gradlew updateGraph" && exit 1
+          echo "::error::Check Graphs failed, please update graphs with: ./gradlew graphUpdate" && exit 1
 
       - name: Push new graphs if available
         if: steps.graphs_verify.outcome == 'failure' && github.event_name == 'pull_request'
