Add clear instruction at CI screenshot tests error output (#1423)
* Add clear instruction
- Your fork's CI will take screenshots for your fork.

Change-Id: I7ea1a437be4f9723fcf71d4d18932f8f44f46fa8

* Remove screenshots to see CI instruction.

Change-Id: Ib12f0ee4ff4faff8287f9ddfd5e533868abca4f8

* Revert "Remove screenshots to see CI instruction."

This reverts commit 36de3be9ba59b50dd7c0ab0f469e38379327b96b.

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -93,7 +93,9 @@ jobs:
         continue-on-error: false
         if: steps.screenshotsverify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
         run: |
-          echo "::error::Screenshot tests failed, please create a PR in your fork first." && exit 1
+          echo "::error::Screenshot tests failed, please create a PR in your fork first." 
+          echo "Your fork's CI will take screenshots for your fork."
+          exit 1
 
       # Runs if previous job failed
       - name: Generate new screenshots if verification failed and it's a PR
